# Используем официальный образ Ubuntu 22.04
FROM ubuntu:22.04

# Указываем кто поддерживает образ, его версию и содержание
LABEL maintainer="lily.potapova.00@mail.ru"
LABEL version="1.0"
LABEL description="Этот образ содержит samtools (версия 1.21), htslib (версия 1.21), libdeflate (версия 1.23), bcftools (версия 1.21), vcftools (версия 0.1.16)."

# Устанавливаем переменную окружения $SOFT
ENV SOFT=/soft

# Создаем директорию, указанную в $SOFT
RUN mkdir -p $SOFT

# Устанавливаем общие пакеты через apt
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    curl \
    git \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libcurl4-gnutls-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

## Установка samtools (версия 1.21)
RUN mkdir -p $SOFT/samtools-1.21 && \
    cd $SOFT/samtools-1.21 && \
    wget https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2 && \
    tar -xjf samtools-1.21.tar.bz2 && \
    cd samtools-1.21 && \
    ./configure --prefix=$SOFT/samtools-1.21 && \
    make -j$(nproc) && \
    make install && \
    rm -rf $SOFT/samtools-1.21/samtools-1.21.tar.bz2

## Установка htslib (версия 1.21)
RUN mkdir -p $SOFT/htslib-1.21 && \
    cd $SOFT/htslib-1.21 && \
    wget https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2 && \
    tar -xjf htslib-1.21.tar.bz2 && \
    cd htslib-1.21 && \
    ./configure --prefix=$SOFT/htslib-1.21 && \
    make -j$(nproc) && \
    make install && \
    rm -rf $SOFT/htslib-1.21/htslib-1.21.tar.bz2

## Установка libdeflate (версия 1.23)
RUN mkdir -p $SOFT/libdeflate-1.23 && \
    cd $SOFT/libdeflate-1.23 && \
    wget https://github.com/ebiggers/libdeflate/archive/refs/tags/v1.23.tar.gz && \
    tar -xzf v1.23.tar.gz && \
    cd libdeflate-1.23 && \
    make -j$(nproc) && \
    make install && \
    rm -rf $SOFT/libdeflate-1.23/v1.23.tar.gz
