name: Download FP_SNPs.txt

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс

jobs:
  download:
    runs-on: ubuntu-latest  
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download ZIP file
      run: |
        curl -o GRAF_files.zip "http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetZip.cgi?zip_name=GRAF_files.zip"

    - name: Unzip the file
      run: |
        unzip GRAF_files.zip -d extracted_files

    - name: Move the required file to the root directory
      run: |
        mv extracted_files/data/FP_SNPs.txt FP_SNPs.txt
        
     - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add FP_SNPs.txt
        git commit -m "Add FP_SNPs.txt file from downloaded archive"
        git push
