name: Download and Extract FP_SNPs

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную через интерфейс GitHub

jobs:
  download-extract-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download GRAF archive
      run: |
        wget -O GRAF_files.tar.gz http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetZip.cgi?zip_name=GRAF_files.tar.gz
    
    - name: Check file type
      run: |
        file GRAF_files.tar.gz

    - name: Extract archive
      run: |
        mkdir -p GRAF_files
        tar -xzf GRAF_files.tar.gz -C GRAF_files

    - name: Check downloaded file content
      run: |
        file GRAF_files/data/FP_SNPs.txt
        echo "First 20 lines of the file:"
        head -n 20 GRAF_files/data/FP_SNPs.txt

    - name: Move FP_SNPs.txt to repository root
      run: |
        mv GRAF_files/data/FP_SNPs.txt FP_SNPs.txt

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add FP_SNPs.txt
        git commit -m "Add FP_SNPs.txt from GRAF archive"
        git push
