name: Docker Build and Run

on:
  workflow_dispatch:  # Ручной запуск

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build -f Dockerfile.ubuntu -t snp-converter .

      # Шаг 3: Запускаем контейнер и скрипт
      - name: Run conversion
        run: |
          docker run \
            -v $(pwd):/app/data \
            snp-converter \
            -i /app/FP_SNPs_10k_GB38_twoAllelsFormat.tsv \
            -o /app/FP_SNPs_10k_GB38_REF_ALT.tsv \
            -r /app/data/ref/GRCh38.d1.vd1_mainChr/sepChrs/

      # Шаг 4: Сохраняем результат как артефакт
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: |
            FP_SNPs_10k_GB38_REF_ALT.tsv
            FP_SNPs_10k_GB38_twoAllelsFormat.tsv
